//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="Service", ConfigurationName="ILineService")]
public interface ILineService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="Service/ILineService/SaveLines", ReplyAction="Service/ILineService/SaveLinesResponse")]
    bool SaveLines(string[] lines);
    
    [System.ServiceModel.OperationContractAttribute(Action="Service/ILineService/SaveLines", ReplyAction="Service/ILineService/SaveLinesResponse")]
    System.Threading.Tasks.Task<bool> SaveLinesAsync(string[] lines);
    
    [System.ServiceModel.OperationContractAttribute(Action="Service/ILineService/FindLines", ReplyAction="Service/ILineService/FindLinesResponse")]
    string[] FindLines(string substring);
    
    [System.ServiceModel.OperationContractAttribute(Action="Service/ILineService/FindLines", ReplyAction="Service/ILineService/FindLinesResponse")]
    System.Threading.Tasks.Task<string[]> FindLinesAsync(string substring);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILineServiceChannel : ILineService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LineServiceClient : System.ServiceModel.ClientBase<ILineService>, ILineService
{
    
    public LineServiceClient()
    {
    }
    
    public LineServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LineServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool SaveLines(string[] lines)
    {
        return base.Channel.SaveLines(lines);
    }
    
    public System.Threading.Tasks.Task<bool> SaveLinesAsync(string[] lines)
    {
        return base.Channel.SaveLinesAsync(lines);
    }
    
    public string[] FindLines(string substring)
    {
        return base.Channel.FindLines(substring);
    }
    
    public System.Threading.Tasks.Task<string[]> FindLinesAsync(string substring)
    {
        return base.Channel.FindLinesAsync(substring);
    }
}
